export enum IconName {
  SearchOutline = 'search-outline',
  Search = 'search',
  HeartOutline = 'heart-outline',
  Heart = 'heart',
  PersonOutline = 'person-outline',
  PersonCircleOutline = 'person-circle-outline',
  PersonCircle = 'person-circle',
  Language = 'language-outline',
  Notifications = 'notifications-outline',
  ThemeSun = 'md-sunny-outline',
  Chat = 'chatbubble-ellipses-outline',
  RadioButtonsOn = 'radio-button-on',
  RadioButtonsOff = 'radio-button-off',
  Add = 'add',
  ChevronForward = 'chevron-forward-outline',
  EyeOutline = 'eye-outline',
  EyeOffOutline = 'eye-off-outline',
  ChevronDown = 'chevron-down-outline',
  Close = 'close-outline',
  CameraOutline = 'camera-outline',
  Camera = 'camera',
  Phone = 'local-phone',
  Person = 'person',
  Back = 'arrow-back-outline',
  BackChevron = 'chevron-back',
  Edit = 'edit',
  Error = 'error-outline',
  List = 'ios-list',
  Location = 'location',
  Delete = 'delete-outline',
  Image = 'images-outline',
  Login = 'ios-log-in-outline',
  Logout = 'ios-log-out-outline',

  Wifi = 'wifi-outline',
  Parking = 'car-outline',
  Pool = 'pool',
  Paw = 'paw-outline',
  Moon = 'moon-outline',
  Home = 'home-outline',
  Leaf = 'leaf-outline',
  Smoking = 'smoking-rooms',
  Child = 'child-care',
  Med = 'medical-outline',
  Pin = 'pin-outline',
  Shirt = 'shirt-outline',
  Kitchen = 'kitchen',
  Snow = 'snow-outline',
  Tv = 'tv-outline',
  Airplane = 'airplane-outline',
  Albums = 'albums-outline',
  AddCircle = 'add-circle-outline',
  AddBlank = 'add-outline',
  RemoveCircle = 'remove-circle-outline',
  Ellipse = 'ellipse-outline',
  Check = 'checkmark-circle-outline',

  Options = 'options-outline',
  Star = 'star',
}

export type IconSet = 'ionicons' | 'material';

export enum ThemeType {
  Light = 'LIGHT',
  Dark = 'DARK',
}
